on:
  create

jobs:
  notify:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl --data-urlencode "message=[@${{github.repository}} ${{github.ref_name}}](${{github.repositoryUrl}/releases/latest) released" ${{secrets.GITTER_CUSTOM_WEBHOOK}}
  
