on: [push, pull_request]

jobs:
  pre-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'

      - run: npm install

      - name: Formatting
        run: npm run format:check

      - name: Linting
        run: npm run lint
  
  branch-test:
    if: github.refname != 'master' && success()
    needs: pre-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'

      - run: npm install

      - name: Formatting
        run: npm run format:check

      - name: Linting
        run: npm run lint

  test:
    if: github.refname == 'master' && success()
    needs: pre-test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest' ]
        node: [ '10', '12', '14', '16' ]
    name: Testing Node ${{ matrix.node }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - run: npm install
      - run: npm test
      - run: npm run coveralls